os:
- osx
- linux
language: generic
sudo: required
dist: trusty
osx_image: xcode7.2
env:
  - SWIFT_VERSION=5.2-SNAPSHOT-2020-01-06-a
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gem install xcpretty-travis-formatter; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
script:
- swift --version
- swift build
- swift test
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild test -scheme SwiftKit | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}; fi