os:
- osx
- linux
language: swift
sudo: required
dist: trusty
osx_image: xcode11.3
env:
  - SWIFT_VERSION=5.2-SNAPSHOT-2020-01-06-a

addons:
  apt:
    packages:
      - graphviz

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gem install xcpretty-travis-formatter; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi

script:
- swift --version
- swift build
- swift test
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild test -scheme SwiftKit | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}; fi