name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  macOS:
    strategy:
      matrix:
        xcode:
          - '11.7'
          - '12.5.1'
          - '13.0'
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: swift test 2>&1 | xcpretty
  linux:
    strategy:
      matrix:
        swift:
          - swift:5.1-bionic
          - swift:5.2-focal
          - swift:5.3-focal
          - swift:5.4-focal
          - swift:5.5-focal
    container: 
      image: ${{ matrix.swift }}
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test 2>&1 | xcpretty