name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  macOS:
    strategy:
      matrix:
        xcode:
          - '11.4'
          - '12'
          - '13.0'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: swift test 2>&1 | xcpretty
  linux:
    strategy:
      matrix:
        swift:
          - swift:5.1
          - swift:5.2
          - swift:5.3
          - swift:5.4
          - swift:5.5
          - swiftlang/swift:nightly-main
        distro:
          - focal
    container: 
      image: ${{ format('{0}-{1}', matrix.swift, matrix.distro) }}
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test