name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  macOS:
    strategy:
      matrix:
        xcode:
          - '11.7'
          - '12.5.1'
          - '13.0'
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: swift test --enable-test-discovery --enable-code-coverage 2>&1 | xcpretty
      - name: Convert profdata to LCOV
        run: |
          xcrun llvm-cov export -format lcov \
            --ignore-filename-regex='/(\.build|Tests|Sources|Snapshots|PerformanceTests)/' \
            -instr-profile=$(dirname $(swift test --show-codecov-path))/default.profdata \
            $(swift build --show-bin-path)/SwiftKitPackageTests.xctest/Contents/MacOS/SwiftKitPackageTests \
            >coverage.lcov
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
          verbose: true
          flags: macos-11 xcode${{ matrix.xcode }}
          env_vars: MD_APPLE_SDK_ROOT,RUNNER_OS,RUNNER_ARCH
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        swift-version:
          - "5.4.2"
          - "5.5"
    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift test
          swift-version: ${{ matrix.swift-version }}
  linux:
    strategy:
      matrix:
        swift:
          - swift:5.2-focal
          - swift:5.3-focal
          - swift:5.4-focal
          - swift:5.5-focal
    container: 
      image: ${{ matrix.swift }}
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery --enable-code-coverage
      - name: Convert profdata to LCOV
        run: |
          llvm-cov export -format lcov \
            --ignore-filename-regex='/(\.build|Tests|Sources|Snapshots|PerformanceTests)/' \
            -instr-profile=$(dirname $(swift test --show-codecov-path))/default.profdata \
            $(swift build --show-bin-path)/SwiftKitPackageTests.xctest \
            >coverage.lcov
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
          verbose: true
          flags: ubuntu-20.04 swift${{ matrix.swift }}
          env_vars: SWIFT_VERSION,SWIFT_PLATFORM,RUNNER_OS,RUNNER_ARCH